import 'bootstrap/dist/css/bootstrap.css';
import '@mantine/dates/styles.css';
import '@mantine/core/styles.css';
import './globals.css';
import { Roboto_Mono } from 'next/font/google';

import { ColorSchemeScript, MantineProvider } from '@mantine/core';

const robotoMono = Roboto_Mono({ subsets: ['latin' ]});

export const metadata = {
  title: 'taskTrax',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={robotoMono.className}>
        <div className="p-4" style={{minWidth: "0.2vw"}}>
          <MantineProvider>{children}</MantineProvider>
        </div>
      </body>
    </html>
  )
}
